### ISSUE TITLE
AttributeError: 'EdgeModel' object has no attribute 'remove_spectralnorm'

### ISSUE THREAD

**Issue by farazBhatti** [Ma-Dan/EdgeConnect-CoreML#1]
Running this line 
`python test.py --checkpoints ./checkpoints/places2 --input ./examples/test/places2 --output ./results
`
produces this error : AttributeError: 'EdgeModel' object has no attribute 'remove_spectralnorm' .
Any suggestions?

**Comment by Ma-Dan** [comment]
Please checkout this modification of remove_spectralnorm.
[https://github.com/Ma-Dan/edge-connect/commit/82163650029a8fa47913928bffd78f97e1439dc4#diff-3395ea8f354fd9c6f69624b5feb17e17R138](https://github.com/Ma-Dan/edge-connect/commit/82163650029a8fa47913928bffd78f97e1439dc4#diff-3395ea8f354fd9c6f69624b5feb17e17R138)

**Comment by farazBhatti** [comment]
@Ma-Dan  so basically you are trying to say to update 
`self.edge_model.remove_spectralnorm()`
to 
`self.edge_model.generator.remove_spectralnorm()` , because function definition of spectralnorm is in class EdgeGenerator of file  src/networks .
Ive updated `self.edge_model.remove_spectralnorm()` into `self.edge_model.generator.remove_spectralnorm()`  and now the model is converted to onnx model . you might also want to apply this update. Thanks for your help
