### ISSUE TITLE
Can't reproduce results

### ISSUE THREAD

**Issue by farazBhatti** [Ma-Dan/EdgeConnect-CoreML#2]
I've tried running this project but can not reproduce the results shown in ReadMe section.
Am i doing something wrong?
Xcode 10.1
Mac 10.14

![Screenshot from 2019-07-04 10-17-30](https://user-images.githubusercontent.com/37732181/60641501-6e2ebe80-9e45-11e9-82dd-17e623e491e4.png)

**Comment by farazBhatti** [comment]
Got it. image must be size 320 x 320 and of .bmp extension. although the code is resizing image internally but some how it doesnot work, so image must be 320*320

**Comment by farazBhatti** [comment]
@Ma-Dan  when ever model is run for the first time it produces results like this 
![60641501-6e2ebe80-9e45-11e9-82dd-17e623e491e4](https://user-images.githubusercontent.com/37732181/61105052-1e2da880-a492-11e9-824c-4ae0060294a6.png)
but on the second go it gives good results. how is it possible, any ideas?
![Screenshot from 2019-07-12 10-46-40](https://user-images.githubusercontent.com/37732181/61105178-8a101100-a492-11e9-9a7e-4a208f9be7f5.png)

**Comment by Ma-Dan** [comment]
Sorry, the old version I used to create this readme gif has no edge detection function applied, so just simply modify
https://github.com/Ma-Dan/EdgeConnect-CoreML/blob/master/EdgeConnect-CoreML/EdgeConnect-CoreML/ViewController.swift#L143
to
`ptrInput[y*width + x + cStride * 1] = 0`
will reproduce the result.
The best solution is porting edge detection algorithm from scikit-image.
And "Apply mask from touch screen input" is only a feature of iPhone app, the mask currently used is simply obtained from the input image which pixel is white, if we can draw mask on touch screen and then apply, this application will be much more convenient.

**Comment by palla89** [comment]
Hi! I have still a different result, can you give me an advice? I see this also after the fix:

![IMG_6065](https://user-images.githubusercontent.com/12301205/62039995-0b88d280-b1f9-11e9-8888-0c6c5fca8647.PNG)

I'm using the image extracted from your gif, in 320x320 and in bmp format.
Any hint?
